[package]
name = "par_fibonacci"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "*"
num-bigint = "*"
num-traits = "*"
clap = {version = "*", features = ["derive"]}
